title: MeowPiE's Lab
description: 프로그래밍하는 냥파이의 냐옹냐옹 끄적끄적 대충쓰는 블로그!
url: https://meowpie.cf
keywords: ["Programming", "Blog", "IT", "GitHub", "Pages", "MeowPiE"]
timezone: Asia/Seoul
permalink: pretty

about: "냥파이의 프로그래밍과 취미생활을 담은 깃허브 페이지 블로그입니다!<br>항상 신기술을 탐구하고 발빠르게 사용하려고 노력하고있는 평범한 학생입니다.<br>현재는 프로그래밍을 비롯해서 잡다한 컴퓨터 정보를 쓰고있습니다;;<br>일주일에 글을 하나는 작성하는게 제 작은 목표입니다.<br>학교생활 적응하느라 블로그에 신경을 쓰지 못하고 있습니다...<br>방문해주셔서 고맙습니다!"

author:
  disqus: meowpies-lab
  email: email@meowpie.cf
  github: MeowPiE
  google_analytics: UA-109470193-1
  name: MeowPiE

neighbors:
  title: ["NewDeaBox"]
  url: ["https://newdeaboxgroup.github.io"]

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-sitemap
  - jekyll-include-cache

kramdown:
  input: GFM

paginate: 10
paginate_path: "/blog/page/:num/"

sass:
  style: compressed
